### ISSUE TITLE
Why dureader testSet Use Acc metric instead of Rouge

### ISSUE THREAD

**Issue by jarheadjoe** [KwanWaiChung/M4LE#7]

**Comment by KwanWaiChung** [comment]
Many LLMs often include unnecessary details in their output, such as starting with phrases like "OK, here is the answer to your question..." or providing excessively long replies when a short phrase is expected. Therefore, we chose to us accuracy instead of Rouge in DuReader and also for other QA tasks, we prefer it over F1. If you have any further questions or comments, please feel free to let us know. Thank you.

**Comment by jarheadjoe** [comment]
When using Acc in dureader, gpt-3.5-16k's score is very low, this is my self test.
![image](https://github.com/KwanWaiChung/M4LE/assets/21330284/c9f99e16-4027-4384-9314-158b6c61c4c3)
This is inconsistent with the results in the appendix of your paper

**Comment by KwanWaiChung** [comment]
Thank you for your suggestion. We have changed the metric to rouge instead in the updated version.
